include:
  - project: 'smartive/ci-templates'
    ref: v1.2.0
    file: '/github/defaults/npm.yml'

variables:
  REPO: 'smartive/react-pwa-toolbox'

create release:
  before_script:
    - npm ci
    - npm run build
